authorizer-app/.dockerignore, authorizer-app/package-lock.json, authorizer-app/src/app/app.module.ts, authorizer-app/src/app/components/rest-source-authorization/rest-source-user-list.component.css, authorizer-app/src/app/components/rest-source-authorization/rest-source-user-list.component.html, authorizer-app/src/app/components/rest-source-authorization/rest-source-user-list.component.ts, authorizer-app/src/styles.css
Adds support for Client side pagination, sorting and filtering.
- 
NOTE: For better performance this should be implemented in the future in backend. #17 
- Closes #14 
- Closes #12 
- Adds pagination, sorting and filtering using mat-table, mat-paginator and mat-form-field
- One form for filtering for any column in the table
- Adds material theme
Here is a gif of how it looks -
=> Add support for pagination, sorting and filtering

README.md, authorizer-app/package.json, build.gradle
=> Release 1.2.0

authorizer-app/package-lock.json, authorizer-app/package.json, authorizer-app/src/app/app.module.ts, authorizer-app/src/app/components/rest-source-authorization/rest-source-user-list-delete-dialog.html, authorizer-app/src/app/components/rest-source-authorization/rest-source-user-list-reset-dialog.html, authorizer-app/src/app/components/rest-source-authorization/rest-source-user-list.component.css, authorizer-app/src/app/components/rest-source-authorization/rest-source-user-list.component.html, authorizer-app/src/app/components/rest-source-authorization/rest-source-user-list.component.ts, authorizer-app/src/app/components/rest-source-authorization/update-rest-source-user.component.html, authorizer-app/src/app/components/rest-source-authorization/update-rest-source-user.component.ts, authorizer-app/src/app/models/rest-source-user.model.ts, authorizer-app/src/app/services/rest-source-user.service.ts, src/main/java/org/radarbase/authorizer/domain/RestSourceUser.java, src/main/java/org/radarbase/authorizer/service/RestSourceUserService.java, src/main/java/org/radarbase/authorizer/service/dto/RestSourceUserPropertiesDTO.java, src/main/java/org/radarbase/authorizer/webapp/resource/RestSourceUserResource.java, src/main/resources/db/changelog/changes/00000000000001_update_schema.xml, src/main/resources/db/changelog/changes/00000000000002_update_schema.xml, src/main/resources/db/changelog/db.changelog-master.yaml
- Adds a version property to user details that is the current time instant as a ISO format string.
- This will enable re-pull of user's data.
Working demo is [here](https://radar-backend.co.uk/rest-sources/authorizer/)
Closes #33
=> Initial implementation for RESET of users

authorizer-app/src/app/components/shared/toolbar/toolbar.component.html
=> Fix logo path

README.md, authorizer-app/src/app/app.module.ts, authorizer-app/src/app/auth.interceptor.ts, authorizer-app/src/app/error.interceptor.ts, build.gradle, docker-compose.yml, docker/etc/managementportal/oauth_client_details.csv, src/main/java/org/radarbase/authorizer/config/AuthTokenValidatorConfig.java, src/main/java/org/radarbase/authorizer/config/RestSourceAuthorizerProperties.java, src/main/java/org/radarbase/authorizer/security/CustomWebSecurityConfigurerAdapter.java, src/main/java/org/radarbase/authorizer/security/JwtAuthenticationFilter.java, src/main/java/org/radarbase/authorizer/service/RestSourceUserService.java, src/main/java/org/radarbase/authorizer/webapp/resource/HealthCheckResource.java, src/main/resources/application.yml
- Adds a simple Authentication Filter to authenticate endpoints and validate token from Management Portal
- Adds a simple health check resource and exclude from Filters
=> Authenticate endpoints

authorizer-app-backend/src/main/java/org/radarbase/authorizer/doa/RestSourceUserRepositoryImpl.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/resources/RestSourceUserResource.kt, authorizer-app/src/app/components/rest-source-authorization/update-rest-source-user.component.ts, authorizer-app/src/app/error.interceptor.ts, authorizer-app/src/app/services/rest-source-user.service.ts
Explicitly handle external-user-id conflict.
=> Handle externalid conflict

authorizer-app-backend/Dockerfile, authorizer-app-backend/src/main/java/org/radarbase/authorizer/doa/RestSourceUserRepository.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/doa/RestSourceUserRepositoryImpl.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/resources/RestSourceUserResource.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/service/RestSourceAuthorizationService.kt
Intends to address part of: https://github.com/RADAR-base/RADAR-REST-Connector/pull/65
=> Invalidate users without valid refresh tokens

authorizer-app-backend/src/main/java/org/radarbase/authorizer/resources/RestSourceUserResource.kt, authorizer-app/src/app/components/rest-source-authorization/rest-source-user-list.component.html, authorizer-app/src/app/components/rest-source-authorization/rest-source-user-list.component.ts, authorizer-app/src/app/components/rest-source-authorization/update-rest-source-user.component.html, authorizer-app/src/app/components/rest-source-authorization/update-rest-source-user.component.ts, docker/etc/rest-source-authorizer/authorizer.yml, docker/etc/rest-source-authorizer/authorizer.yml.template
- Refresh token if token is expired
- Fix issues with userID not appearing on update dialog
- Refresh correct page after reset and delete operations
- update authorizer.yml to correct format.
- remove redundant button.
=> Minor fixes

authorizer-app-backend/src/main/java/org/radarbase/authorizer/inject/AuthorizerResourceEnhancer.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/resources/RestSourceUserResource.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/resources/SourceClientResource.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/util/StateStore.kt
Fixes an issue where a re-login during authorization attempt removes the & symbol.
=> Handle backends that do not always process multiple states

authorizer-app-backend/src/main/java/org/radarbase/authorizer/doa/RestSourceUserRepositoryImpl.kt
=> Allow overriding existing user if it does not have a project

authorizer-app/src/app/components/rest-source-authorization/rest-source-user-list.component.ts
This should solve the issue with logging in as PROJECT_ADMIN
=> Fix querying undefined project

.editorconfig, authorizer-app-backend/build.gradle.kts, authorizer-app-backend/src/main/java/org/radarbase/authorizer/Config.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/api/ApiDeclarations.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/api/Project.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/api/RestSourceUserMapper.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/doa/RestSourceUserRepositoryImpl.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/inject/AuthorizerResourceEnhancer.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/inject/ManagementPortalEnhancerFactory.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/resources/ProjectResource.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/resources/RestSourceUserResource.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/resources/SourceClientResource.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/service/RestSourceAuthorizationService.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/util/StateStore.kt
Adds kotlin linter to check style guide.
=> Enable Kotlin linter

authorizer-app/src/app/components/rest-source-authorization/rest-source-user-list.component.html, authorizer-app/src/app/components/rest-source-authorization/rest-source-user-list.component.ts, authorizer-app/src/app/components/rest-source-authorization/update-rest-source-user.component.html, authorizer-app/src/app/services/rest-source-user.service.ts
- Show reset version info in user info page (or `update-rest-source-user` component) (Solves #109)
- Encode uri when getting projects to allow project ids to have whitespaces (Solves #108)
- Show complete user id in `update-rest-source-user` component and show a tooltip with the complete user id in the user list component (Solves #107)
=> Minor fixes 

authorizer-app-backend/src/main/java/org/radarbase/authorizer/api/ApiDeclarations.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/doa/RestSourceUserRepositoryImpl.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/resources/RestSourceUserResource.kt
- Change maximum page number to Integer.MAX_VALUE for pulling all users
=> Fix maximum page number

.github/workflows/main.yml, .github/workflows/release.yml, authorizer-app-backend/Dockerfile, authorizer-app-backend/src/main/java/org/radarbase/authorizer/Main.kt, authorizer-app/Dockerfile
- Use buildx for multiplatform build
- Add standard docked container labels
- add release workflow
- test curl and app runtime docker availability
- Avoid docker pull limit by logging in with secrets `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN`
=> Enhance GitHub actions

authorizer-app-backend/src/main/java/org/radarbase/authorizer/doa/RestSourceUserRepository.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/doa/RestSourceUserRepositoryImpl.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/resources/ProjectResource.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/resources/RestSourceUserResource.kt, authorizer-app/Dockerfile, authorizer-app/src/app/app.module.ts, authorizer-app/src/app/components/rest-source-authorization/rest-source-user-dashboard.component.css, authorizer-app/src/app/components/rest-source-authorization/rest-source-user-dashboard.component.html, authorizer-app/src/app/components/rest-source-authorization/rest-source-user-dashboard.component.ts, authorizer-app/src/app/components/rest-source-authorization/rest-source-user-list.component.css, authorizer-app/src/app/components/rest-source-authorization/rest-source-user-list.component.html, authorizer-app/src/app/components/rest-source-authorization/rest-source-user-list.component.ts, authorizer-app/src/app/components/rest-source-authorization/rest-source-user-registration-form.component.html, authorizer-app/src/app/components/rest-source-authorization/rest-source-user-registration-form.component.ts, authorizer-app/src/app/models/rest-source-user.model.ts, authorizer-app/src/app/services/rest-source-user.service.ts
Fixes #106, including the error screenshot. Changes:
- Added `search` parameter to `/users` to filter users by user ID or external ID.
- Use server-side search parameter in user list to get the right filtering.
- Bumped nginx version
- Split the frontend user list component into a dashboard page and a user list subcomponent.
- Show "No users found" in table if no users are found, instead
- Set default page size option to 50
- Disable authorization button if no source type is selected
- Use rxjs in user list to trigger user list updates due to paging, filtering or modification.
- Sorting only affects only the current page.
=> Fix user filtering

authorizer-app-backend/src/main/java/org/radarbase/authorizer/doa/RestSourceUserRepositoryImpl.kt
=> Fix query syntax

.github/workflows/main.yml, .github/workflows/release.yml, authorizer-app-backend/Dockerfile, authorizer-app-backend/build.gradle.kts, authorizer-app-backend/src/main/java/org/radarbase/authorizer/Config.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/inject/AuthorizerResourceEnhancer.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/inject/ManagementPortalEnhancerFactory.kt, authorizer-app/package.json, build.gradle.kts, gradle.properties, gradle/wrapper/gradle-wrapper.properties
- Updated dependencies including `log4j` vulnerable dependency
=> Release 3.2.2

.github/workflows/main.yml, authorizer-app-backend/Dockerfile
- Fix Github actions
- Test arm build in main workflow
=> Fix Github actions

.github/workflows/main.yml, .github/workflows/release.yml, authorizer-app-backend/src/main/java/org/radarbase/authorizer/util/OauthSignature.kt, authorizer-app/Dockerfile, authorizer-app/package.json, authorizer-app/src/app/admin/containers/user-dialog/user-dialog.component.ts, authorizer-app/src/app/admin/services/user.service.ts, authorizer-app/src/app/shared/containers/authorization-complete-page/authorization-complete-page.component.ts, authorizer-app/src/app/shared/enums/storage-item.ts, build.gradle.kts
- Updates Github actions
- Fixes Garmin OAuth1 authentication
=> Release 4.0.1

authorizer-app-backend/src/main/java/org/radarbase/authorizer/resources/RestSourceUserResource.kt
=> only return authorized users by default

authorizer-app-backend/src/main/resources/db/changelog/changes/20211008113000_add_registration_created_at.xml, authorizer-app/package.json, authorizer-app/yarn.lock, build.gradle.kts, gradle.properties
Changes since version 4.1.2:
- Fixed liquidate configuration issue on PostgreSQL
- Bumped dependencies
=> Release 4.1.3

authorizer-app-backend/src/main/java/org/radarbase/authorizer/api/ApiDeclarations.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/service/OuraAuthorizationService.kt
Reverts RADAR-base/RADAR-Rest-Source-Auth#253
=> Revert "Updated getExternalId function for Oura Oauth"

authorizer-app-backend/src/main/java/org/radarbase/authorizer/api/ApiDeclarations.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/service/OuraAuthorizationService.kt, authorizer-app/package.json, buildSrc/src/main/kotlin/Versions.kt
- Updated pulling of Oura external ID
=> Release 4.4.1

authorizer-app/src/app/auth/services/management-portal-auth.service.ts
Small changes for ory integration
=> ory integration

buildSrc/src/main/kotlin/Versions.kt
Mistake in #259, the dependency should be on jersey 0.11.**1**-snapshot
=> Bump jersey

authorizer-app-backend/src/main/java/org/radarbase/authorizer/api/ApiDeclarations.kt
- Allow null properties for `OuraAuthUserId`
=> Allow null properties for OuraAuthUserId

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Versions.kt
Changes:
- #274 Fix the problems with radar-jersey returning malformed www-authenticate headers.
=> Release 4.4.3

authorizer-app/Dockerfile, authorizer-app/package.json, buildSrc/src/main/kotlin/Versions.kt
=> [security] Change docker image base and prepare for 4.4.4 release

authorizer-app/package.json, buildSrc/src/main/kotlin/Versions.kt
=> version/radar-jersey-0.12.1 and prepare for release 4.4.7

.github/workflows/scheduled-snyk.yaml, .github/workflows/snyk.yaml
=> Fix node config in action

authorizer-app/package.json, buildSrc/src/main/kotlin/Versions.kt
- Sync release changes with dev
=> Sync release changes with dev

authorizer-app-backend/src/main/java/org/radarbase/authorizer/config/AuthorizerServiceConfig.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/doa/RestSourceUserRepository.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/doa/RestSourceUserRepositoryImpl.kt, authorizer-app-backend/src/main/java/org/radarbase/authorizer/lifecycle/UserSyncLifecycleManager.kt
- Add UserSyncLifecycleManager to periodically cleanup rest source users that have been deleted in Management Portal to ensure consistent state
Solves #279
=> Add periodic user cleanup
